<h2>Inserir Categoria</h2>

<?php 
    /*
     * @var $form \Zend\Form\Form
     */
    $form = $this->form;
    
    if ($this->success)
        echo '<div class="alert alert-success">' . $this->success[0] . '<button type="button" class="close" data-dismiss="alert">x</buttton></div>';
    
    if ($this->error)
        echo '<div class="alert alert-danger">' . $this->error[0] . '<button type="button" class="close" data-dismiss="alert">x</buttton></div>';
    

    $this->formElementErrors()
        ->setMessageOpenFormat('<div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert">x</buttton>')
        ->setMessageCloseString('</div>')
        ->render($form);

    $form->setAttribute('action', $this->url('categoria/default', array('controller' => 'categoria', 'action'=>'insert')));
    
    $form->prepare();
    echo $this->form()->openTag($form);
    
    echo $this->formCollection($form);
    
    echo $this->form()->closeTag();

?>